AppWeb/Models/AlunoModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace AppWeb.Models
{
    public class AlunoModel
    {
        [Key]
        public int AlunoId {  get; set; }
        public string NomeAluno { get; set; }

        public  Prova Prova { get; set; }
    }
}

AppWeb/Models/ErrorViewModel.cs
using System;

namespace AppWeb.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

AppWeb/Models/Prova.cs
using System.ComponentModel.DataAnnotations;

namespace AppWeb.Models
{
    public class Prova
    {
        [Key]
        public int ProvaId { get; set; }
        public string Materia { get; set; }
        public double Nota { get; set; }


        public  AlunoModel Aluno { get; set; }
        public int AlunoId { get; set; }

    }
}

AppWeb/Controllers/AppWebController.cs
using AppWeb.ClassContext;
using AppWeb.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AppWeb.Controllers
{
    public class AppWebController : Controller
    {
        private readonly AppWebContext contexto;

        public AppWebController(AppWebContext contexto)
        {
            this.contexto = contexto;
        }

        public IActionResult Alunos()
        {
            return View();
        }
        
        [HttpPost]
        public IActionResult Alunos(AlunoModel aluno)
        {

            if (ModelState.IsValid)
            {
                contexto.Aluno.Add(aluno);
                contexto.SaveChanges();
                return RedirectToAction("Provas",aluno);


            }
            return View();



        }

        public IActionResult Provas()
        {
            return View();
        }



        [HttpPost]
        public IActionResult Provas(Prova prova,AlunoModel aluno)
        {
            Prova provas = new Prova();

            provas.Materia = prova.Materia;
            provas.Nota = prova.Nota;
            provas.AlunoId = aluno.AlunoId;

            contexto.Add(provas);
            contexto.SaveChanges();

            return View();
           
        }
    }
}

AppWeb/Controllers/HomeController.cs
using AppWeb.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace AppWeb.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

AppWeb/Views/AppWeb/Alunos.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}


@model AlunoModel;

<form method="post" class="accordion">
    <label>Nome Do Aluno</label>
    <br />
    <input asp-for="@Model.NomeAluno" type="text" />
    <br />
    <br />

    <input type="submit"  value="Cadastrar"  formmethod="post" class="btn btn-success" />







</form>

AppWeb/Views/AppWeb/Provas.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@model Prova;


<form method="post" class="accordion">
    <label>Materia : </label>
    <br />
    <input asp-for="@Model.Materia" type="text" />
    <br />
    <br />
    <label>Nota : </label>
    <br />
    <input asp-for="@Model.Nota" type="text" />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <input type="submit" value="Cadastrar" formmethod="post" class="btn btn-success" />





</form>

AppWeb/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

AppWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AppWeb</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AppWeb</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-lg-start">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-black-50" asp-area="" asp-controller="AppWeb" asp-action="Alunos">Alunos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-black-50" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - AppWeb - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>